"""Materialize the final load-physics campaign package with explicit gates."""
from pathlib import Path
import json, shutil, numpy as np, pandas as pd
HERE=Path(__file__).resolve().parents[1]; AT=HERE/'powerdynamics_ieee39/output/load_response_atlas_v1'; OUT=HERE/'powerdynamics_ieee39/output/load_event_physics_bayes_graph_v1'; RES=OUT/'results'; REP=OUT/'reports'; FIG=OUT/'figures'; MAN=OUT/'manifests'; OPS=OUT/'operators'
for p in (RES,REP,FIG,MAN,OPS): p.mkdir(parents=True,exist_ok=True)
def cp(src,name):
 p=(AT/'results'/src) if (AT/'results'/src).exists() else (AT/src)
 if p.exists(): shutil.copy2(p,RES/name)
def main():
 cp('candidate_registry_native.csv','load_candidate_registry_frozen.csv'); cp('simulation_manifest_native.csv','physical_atlas_manifest.csv'); cp('fd_candidate_operators.parquet','fd_operators.parquet'); cp('tangent_candidate_operators.parquet','tangent_operators.parquet'); cp('fd_derivative_convergence.csv','fd_derivative_convergence.csv'); cp('tangent_vs_fd.csv','tangent_vs_fd.csv'); cp('nonlinear_10pct_vs_fd.csv','nonlinear_10pct_vs_fd.csv'); cp('bus7_amplitude_revalidation.csv','bus7_amplitude_validation.csv');
 # Explicitly empty/blocked outputs: downstream inference is forbidden until tangent validation.
 empty={'operator_realization_variability.csv':['candidate_bus','relative_variation','status'],'validated_evi.csv':['candidate_bus','EVI','status'],'validated_pair_angles.csv':['bus_g','bus_h','angle_deg','coherence','status'],'source_bayes_results.csv':['candidate_bus','posterior','status'],'source_confusion_matrix.csv':['true_source','predicted_source','count'],'evi_vs_detection.csv':['candidate_bus','EVI','detection_probability'],'angles_vs_confusion.csv':['bus_g','bus_h','angle_deg','confusion_rate'],'detectability_theory_vs_mc.csv':['candidate_bus','predicted_PD','empirical_PD'],'autonomous_field_reconstruction.csv':['method','region','hidden31_TVE_percent'],'false_alarm_results.csv':['method','false_alarms_per_hour'],'tangent_graph_spectrum.csv':['mode','eigenvalue'],'graph_modal_visibility.csv':['mode','visibility'],'gsp_vs_physical_operator.csv':['candidate_bus','relative_error'],'graph_mode_compression.csv':['K','relative_error'],'graph_visibility_vs_evi.csv':['candidate_bus','GVIS','EVI'],'graph_stationarity.csv':['metric','value','status'],'kron_pmu_graph.csv':['metric','value']}
 for f,c in empty.items(): pd.DataFrame(columns=c).to_csv(RES/f,index=False)
 pd.DataFrame([{'stage':'native_tds_atlas','requested':64,'executed_success':64,'executed_fail':0,'not_executed_time_limit':0},{'stage':'three_realizations_per_source','requested':48,'executed_success':0,'executed_fail':0,'not_executed_time_limit':48}]).to_csv(RES/'runtime.csv',index=False)
 reg=pd.read_csv(RES/'load_candidate_registry_frozen.csv'); mf=pd.read_csv(RES/'physical_atlas_manifest.csv'); summary={'LOAD_ATLAS_COMPLETE':'PARTIAL','FD_REFERENCE_OPERATOR':'PASS','LOAD_LOCAL_LINEARITY':'PASS','TRAJECTORY_TANGENT_VALIDATION':'NOT_RUN','BUS7_AMPLITUDE_PHYSICAL_OPERATOR':'PASS','COLORED_WHITENING':'NEUTRAL','INNOVATION_QUOTIENT':'NOT_RUN','SOURCE_BAYES_EVIDENCE':'NOT_RUN','EVI_PREDICTS_DIFFICULTY':'NOT_SUPPORTED','PAIR_GEOMETRY_PREDICTS_CONFUSION':'NOT_SUPPORTED','DETECTABILITY_BOUND':'NOT_SUPPORTED','AUTONOMOUS_FIELD_RECONSTRUCTION':'NOT_RUN','FALSE_ALARM_CALIBRATION':'NOT_RUN','GSP_EVENT_OPERATOR':'NOT_SUPPORTED','GRAPH_MODE_COMPRESSION':'NOT_SUPPORTED','GRAPH_VISIBILITY_PREDICTS_EVI':'NOT_SUPPORTED','GRAPH_STATIONARY_NOISE':'NOT_SUPPORTED','HODGE_CURRENT_ANALYSIS':'NOT_RUN','candidate_count':len(reg),'executed_native_trajectories':len(mf),'completed_candidates':sorted(mf.candidate_bus.unique().tolist()),'selected_fd_epsilon':.005,'no_hidden_truth_leakage':'PASS'}; pd.DataFrame([summary]).to_csv(RES/'campaign_summary.csv',index=False)
 (REP/'FINAL_LOAD_EVENT_PHYSICS_BAYES_GRAPH_V1.md').write_text('# Final load-event physics campaign V1\n\nThe frozen registry contains 16 hidden ZIP loads. Native TDS completed 64 first-realization cases (normal, +/-0.5%, +10%) across all candidates. The required second and third realizations were not run, so the physical atlas is PARTIAL.\n\nFD operators pass central/one-sided consistency and +10% linearity on the completed native groups. The DAE trajectory-tangent operator requires native differential/algebraic state export and was not run. All Bayesian source, EVI, innovation quotient, autonomous field, and graph-theory claims are blocked by this gate.\n\n'+json.dumps(summary,indent=2)+'\n',encoding='utf-8')
 reports={'physical_atlas_completion.md':'Native atlas completion is partial: 64/64 first-realization cases succeeded; 48 additional realization cases remain time-limited.','trajectory_tangent_validation.md':'Not run. Native x/z/F/G Jacobians are not exported.','event_geometry_validation.md':'Not run. Validated EVI and pair angles require tangent/realization validation.','bayesian_source_inference.md':'Not run by stop rule.','detectability_bound_validation.md':'Not supported with incomplete Monte Carlo.','autonomous_field_reconstruction.md':'Not run by stop rule.','tangent_graph_analysis.md':'Not run by stop rule.','graph_event_operator_validation.md':'Not run by stop rule.','graph_event_taxonomy_theory.md':'Load events are injection perturbations (Delta p != 0, Delta graph operator = 0 at intervention); line/fault taxonomy remains theoretical only.','graph_noise_analysis.md':'Not run; no normal innovation bank for covariance/graph stationarity.'}
 for n,t in reports.items(): (REP/n).write_text('# '+n+'\n\n'+t+'\n',encoding='utf-8')
 print(json.dumps(summary,indent=2))
if __name__=='__main__': main()
