"""FIRST-FLOW-HESSIAN-CLOSURE-V1 post-processing.

This module is deliberately an audit, rather than an estimator.  The Julia
producer records the exact production callback/first-flow map at the first
canonical sample.  We use Richardson extrapolation as the independent
reference, compare every source/cross direction with the variational state
export, and then apply only the resulting initial-condition correction to the
already frozen analytic continuation.  No new PowerDynamics trajectories or
statistical tuning are performed here.
"""
from __future__ import annotations

import json
import math
import re
import shutil
import subprocess
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.linalg import expm

HERE = Path(__file__).resolve().parents[1]
PD = HERE / "powerdynamics_ieee39"
ROOT = PD / "output" / "first_flow_hessian_closure_v1"
EXTERNAL = Path(r"C:\Users\walla\Documents\output\first_flow_hessian_closure_v1")
MAP = ROOT / "state_maps"
RES, REP, FIG, REVIEW = (ROOT / x for x in ("results", "reports", "figures", "CHATGPT_REVIEW"))
for p in (RES, REP, FIG, REVIEW):
    p.mkdir(parents=True, exist_ok=True)

BUSES = [3, 4, 7, 8, 12, 15, 16, 18, 20, 21, 23, 24, 25, 26, 27, 28]
PAIRS = list(combinations(BUSES, 2))
OPS = [("op_m035", 0.35, "analytic_op_m035_state", "analytic_opcond_m035_t120"),
       ("op_m085", 0.85, "analytic_op_m085_state", "analytic_opcond_m085_t120"),
       ("op_m125", 1.25, "analytic_op_m125_state", "analytic_opcond_m125_t120")]
H5, H2 = 0.005, 0.0025
DT = 1.0 / 30.0


def _csv_vec(path: Path) -> np.ndarray:
    d = pd.read_csv(path)
    cols = [c for c in d.columns if re.fullmatch(r"u\d+|x\d+", str(c))]
    if not cols:
        # State exports have x1..x192 without a metadata row in some versions.
        cols = [c for c in d.columns if str(c).startswith(("u", "x"))]
    return d[cols].iloc[-1].to_numpy(float)


def _token(x: float) -> str:
    return str(x).replace("-", "m").replace(".", "p")


def map_path(op: str, kind: str, i: int, j: int | None, ai: float, aj: float) -> Path:
    stem = f"{kind}_{i}" + (f"_{j}" if j is not None else "") + f"_ai{_token(ai)}_aj{_token(aj)}.csv"
    return MAP / op / stem


def rel(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.linalg.norm(a - b) / max(np.linalg.norm(a), 1e-30))


def cos(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / max(np.linalg.norm(a) * np.linalg.norm(b), 1e-30))


def _copy_external() -> None:
    """Copy producer artifacts generated by the include-string wrapper.

    The wrapper's first historical invocation resolved ``@__DIR__`` against
    the Julia working directory, so its resumable output is outside the git
    tree.  Copying is safe and preserves the external tree as an audit
    provenance source.
    """
    if EXTERNAL.exists():
        MAP.mkdir(parents=True, exist_ok=True)
        src = EXTERNAL / "state_maps"
        if src.exists():
            for d in src.glob("op_*"):
                dst = MAP / d.name
                dst.mkdir(parents=True, exist_ok=True)
                for f in d.glob("*.csv"):
                    shutil.copy2(f, dst / f.name)
        if (EXTERNAL / "results" / "ad_feasibility.csv").exists():
            shutil.copy2(EXTERNAL / "results" / "ad_feasibility.csv", RES / "ad_feasibility.csv")


def _all_maps(op: str) -> list[Path]:
    out = []
    for p in sorted((MAP / op).glob("*.csv")):
        if p.name in {"baseline.csv", "manifest.csv", "state_manifest.csv"}:
            continue
        try:
            if len(_csv_vec(p)) == 192:
                out.append(p)
        except Exception:
            pass
    return out


def _self_derivatives(op: str, b: int):
    base = _csv_vec(MAP / op / "baseline.csv")
    p5, m5 = _csv_vec(map_path(op, "self", b, None, H5, 0.0)), _csv_vec(map_path(op, "self", b, None, -H5, 0.0))
    p2, m2 = _csv_vec(map_path(op, "self", b, None, H2, 0.0)), _csv_vec(map_path(op, "self", b, None, -H2, 0.0))
    d5, d2 = (p5 - m5) / (2 * H5), (p2 - m2) / (2 * H2)
    q5, q2 = (p5 - 2 * base + m5) / H5**2, (p2 - 2 * base + m2) / H2**2
    return (4 * d2 - d5) / 3, (4 * q2 - q5) / 3, np.linalg.norm(d2 - d5), np.linalg.norm(q2 - q5)


def _cross_derivative(op: str, i: int, j: int, h: float) -> np.ndarray:
    vals = {}
    for si, sj in ((1, 1), (1, -1), (-1, 1), (-1, -1)):
        vals[(si, sj)] = _csv_vec(map_path(op, "cross", i, j, si * h, sj * h))
    return (vals[(1, 1)] - vals[(1, -1)] - vals[(-1, 1)] + vals[(-1, -1)]) / (4 * h * h)


def _cross_derivatives(op: str, i: int, j: int):
    c5, c2 = _cross_derivative(op, i, j, H5), _cross_derivative(op, i, j, H2)
    return (4 * c2 - c5) / 3, np.linalg.norm(c2 - c5)


def _state_export(state_tag: str, name: str) -> np.ndarray:
    return _csv_vec(PD / "output" / "second_order_op_robustness_v1" / state_tag / "results" / name)


def _read_meta(state_tag: str):
    md = PD / "output" / "second_order_op_robustness_v1" / state_tag / "metadata"
    A = pd.read_csv(md / "A_full.csv", header=None).to_numpy(float)
    M = pd.read_csv(md / "mass_matrix.csv", header=None).to_numpy(float)
    order = pd.read_csv(md / "state_order.csv")
    C = pd.read_csv(md.parent.parent / state_tag / "results" / "C_pmu_frozen.csv", header=None).to_numpy(float)
    return A, M, order, C


def _state_to_output(v: np.ndarray, C: np.ndarray) -> np.ndarray:
    return C @ v


def _reduced(A: np.ndarray, M: np.ndarray):
    # State exports are ordered algebraic first, differential second in the
    # native metadata.  The descriptor reduction is A_dd-A_da A_aa^-1 A_ad.
    alg = np.flatnonzero(np.isclose(np.diag(M), 0.0))
    dif = np.flatnonzero(~np.isclose(np.diag(M), 0.0))
    Aaa, Aad, Ada, Add = A[np.ix_(alg, alg)], A[np.ix_(alg, dif)], A[np.ix_(dif, alg)], A[np.ix_(dif, dif)]
    As = Add - Ada @ np.linalg.solve(Aaa, Aad)
    return alg, dif, As, Aaa, Aad


def _propagate(e: np.ndarray, nframes: int, A: np.ndarray, M: np.ndarray):
    alg, dif, As, Aaa, Aad = _reduced(A, M)
    ed = e[dif]
    E = expm(As * DT)
    out = np.zeros((nframes, len(e)))
    # Dictionary row 0 is the callback-time/pre-event baseline.  The exact
    # production map is first observed at row 1 (t1=tau+dt), so the mismatch
    # must not be injected one sample early.
    for k in range(nframes):
        if k == 0:
            continue
        edk = np.linalg.matrix_power(E, k - 1) @ ed
        eak = -np.linalg.solve(Aaa, Aad @ edk)
        out[k, dif], out[k, alg] = edk, eak
    return out


def _build_corrected_dictionaries(op: str, state_tag: str, cond_tag: str, validation_rows, first_rows, second_rows):
    A, M, order, C = _read_meta(state_tag)
    olddir = PD / "output" / "second_order_op_robustness_v1" / cond_tag / "results"
    D = pd.read_csv(olddir / "analytic_D_all.csv", header=None).to_numpy(float)
    Q = pd.read_csv(olddir / "analytic_Q_self_all.csv", header=None).to_numpy(float)
    QC = pd.read_csv(olddir / "analytic_Q_cross_all.csv", header=None).to_numpy(float)
    arrays = {"D": D.copy(), "Q": Q.copy(), "Qcross": QC.copy()}
    for b in BUSES:
        ex = validation_rows[(validation_rows.op_tag == op) & (validation_rows.direction == f"self_{b}") & (validation_rows.derivative_order == 1)]
        if len(ex):
            e1 = _state_export(state_tag, f"state_first_self_{b}.csv")
            old1 = _state_export(state_tag, f"state_first_self_{b}.csv")
            # The producer's state_first is the variational instantaneous
            # map; the Richardson vector is the exact production map.
            exact1 = ex.iloc[0]["_vec_exact"]
            corr = _propagate(exact1 - old1, 120, A, M)
            arrays["D"][:, BUSES.index(b)] += np.asarray([C @ x for x in corr]) .reshape(-1)
    # For second order the state export is the raw u_ij.  Self Q carries the
    # Taylor 1/2 coefficient, while cross Qij carries the raw mixed term.
    for b in BUSES:
        ex = validation_rows[(validation_rows.op_tag == op) & (validation_rows.direction == f"self_{b}") & (validation_rows.derivative_order == 2)]
        if len(ex):
            old2 = _state_export(state_tag, f"state_second_self_{b}.csv")
            exact2 = ex.iloc[0]["_vec_exact"]
            corr = _propagate(exact2 - old2, 120, A, M)
            arrays["Q"][:, BUSES.index(b)] += 0.5 * np.asarray([C @ x for x in corr]).reshape(-1)
    for k, (i, j) in enumerate(PAIRS):
        ex = validation_rows[(validation_rows.op_tag == op) & (validation_rows.direction == f"cross_{i}_{j}") & (validation_rows.derivative_order == 2)]
        if len(ex):
            old2 = _state_export(state_tag, f"state_second_cross_{i}_{j}.csv")
            exact2 = ex.iloc[0]["_vec_exact"]
            corr = _propagate(exact2 - old2, 120, A, M)
            arrays["Qcross"][:, k] += np.asarray([C @ x for x in corr]).reshape(-1)
    out = RES / f"corrected_dictionary_{op}.npz"
    np.savez_compressed(out, **arrays)
    return arrays, A, M, C


def _profile_fast(y: np.ndarray, D: np.ndarray, var: np.ndarray, horizon: int, support: tuple[int, ...]):
    """Profile a linear competing signature with precomputed small solves."""
    yw = _ar1_whiten(y[:32*horizon], var)
    best = (float("inf"), "", ())
    for b in BUSES:
        if b in support:
            continue
        A = _ar1_whiten(D[:32*horizon, BUSES.index(b)], var)
        aa = float(A @ yw / max(A @ A, 1e-30)); val = float(np.sum((yw - A * aa) ** 2))
        if val < best[0]: best = (val, "single", (b,))
    for sp in PAIRS:
        if set(sp) == set(support):
            continue
        A = np.column_stack([_ar1_whiten(D[:32*horizon, BUSES.index(b)], var) for b in sp])
        aa = np.linalg.lstsq(A, yw, rcond=1e-12)[0]; val = float(np.sum((yw - A @ aa) ** 2))
        if val < best[0]: best = (val, "double", sp)
    return best


def _ar1_whiten(x: np.ndarray, var: np.ndarray, rho: float = 0.3512083596) -> np.ndarray:
    x = np.asarray(x, float).reshape(-1, 32); s = np.sqrt(np.maximum(var, 1e-30)); z = np.empty_like(x)
    z[0] = x[0] / s
    if len(x) > 1: z[1:] = (x[1:] - rho * x[:-1]) / (s * np.sqrt(1 - rho * rho))
    return z.reshape(-1)


def _model_array(arr: dict, support: tuple[int, ...], ai: float, aj: float, nframes: int) -> np.ndarray:
    D, Q, QC = arr["D"], arr["Q"], arr["Qcross"]
    i, n = BUSES.index(support[0]), 32 * nframes
    out = ai * D[:n, i] + ai * ai * Q[:n, i]
    if len(support) > 1:
        j = BUSES.index(support[1])
        out = out + aj * D[:n, j] + aj * aj * Q[:n, j] + ai * aj * QC[:n, PAIRS.index(tuple(sorted(support)))]
    return out


def _parse_physical_name(fp: Path):
    m = re.match(r"PAIR_(\d+)_(\d+)_AI([m\d\.p]+)_AJ([m\d\.p]+)_R1", fp.stem)
    if not m:
        return None
    def pa(s): return float(s.replace("m", "-").replace("p", "."))
    return int(m.group(1)), int(m.group(2)), pa(m.group(3)), pa(m.group(4))


def _physical_replay(corrected):
    """Replay all existing TDS trajectories against old and corrected maps."""
    import sys
    sys.path.insert(0, str(HERE))
    from scripts import e06h_corrected_m6_static as h6
    src = PD / "output" / "t120_multi_op_independent_validation_v1" / "physical"
    vnom, _, _, _, meta = h6.load_nominal(); rows = h6.load_branch_rows(vnom, meta["y0"])
    var_path = PD / "output" / "load_multi_bayes_v1" / "results" / "load_multi_whitening_channels.csv"
    var = pd.read_csv(var_path).sort_values("channel").variance.to_numpy(float)
    horizons = [30, 45, 60, 90, 120]
    out, eta = [], []
    for op, _, state_tag, cond_tag in OPS:
        rr = src / op / "physical" / "results"; arr = corrected[op][0]
        if not rr.exists(): continue
        base_candidates = list(rr.glob("PAIR_3_4_AIm0p0_AJ0p0_R1.csv"))
        if not base_candidates: continue
        base_fp = rr / "PAIR_3_4_AIm0p0_AJ0p0_R1.csv"
        y0 = (__import__("scripts.t120_op_conditioned_manifold_closure_v1", fromlist=["load_bank"]).load_bank(base_fp, rows)
              if base_fp.exists() else None)
        olddir = PD / "output" / "second_order_op_robustness_v1" / cond_tag / "results"
        Dold = pd.read_csv(olddir / "analytic_D_all.csv", header=None).to_numpy(float)
        Qold = pd.read_csv(olddir / "analytic_Q_self_all.csv", header=None).to_numpy(float)
        QCold = pd.read_csv(olddir / "analytic_Q_cross_all.csv", header=None).to_numpy(float)
        oldarr = {"D": Dold, "Q": Qold, "Qcross": QCold}
        for fp in sorted(rr.glob("PAIR_*.csv")):
            parsed = _parse_physical_name(fp)
            if parsed is None: continue
            i, j, ai, aj = parsed
            y = __import__("scripts.t120_op_conditioned_manifold_closure_v1", fromlist=["load_bank"]).load_bank(fp, rows)
            if i == 3 and j == 4 and abs(ai) < 1e-15 and abs(aj) < 1e-15: continue
            if y0 is None: continue
            target = y - y0; support = (i, j) if j else (i,)
            if j == 0:  # single-event files are retained as controls
                support = (i,); aj = 0.0
            for h in horizons:
                n = 32 * h
                mu_c = _model_array(arr, support, ai, aj, h)
                # Historical OP-conditioned dictionary is the uncorrected
                # comparator; corrected arrays differ only by the exact t1
                # state-map mismatch propagated homogeneously.
                mu_o = _model_array(oldarr, support, ai, aj, h)
                for lab, mu in (("old_conditioned", mu_o), ("corrected_conditioned", mu_c)):
                    err = target[:n] - mu
                    out.append({"op_tag": op, "pair": f"{i}-{j}", "ai": ai, "aj": aj, "horizon": h, "model": lab,
                                "raw_relative_error": float(np.linalg.norm(err) / max(np.linalg.norm(target[:n]), 1e-30)),
                                "whitened_error": float(np.linalg.norm(_ar1_whiten(err, var))), "cosine": cos(target[:n], mu),
                                "source": "stored_TDS_bank", "new_tds_generated": False})
                # Eta uses the corrected local model and a linear profiled
                # competing-manifold margin, exactly as the historical closure.
                prof, ct, cs = _profile_fast(mu_c, arr["D"], var, h, support)
                eta.append({"op_tag": op, "pair": f"{i}-{j}", "ai": ai, "aj": aj, "horizon": h,
                            "eta_old": float(np.linalg.norm(_ar1_whiten(target[:n] - mu_o, var)) / math.sqrt(max(_profile_fast(mu_o, Dold, var, h, support)[0], 1e-30))),
                            "eta_corrected": float(np.linalg.norm(_ar1_whiten(target[:n] - mu_c, var)) / math.sqrt(max(prof, 1e-30))),
                            "margin_corrected_sq": prof, "nearest_competitor": ct + ":" + "-".join(map(str, cs)), "new_tds_generated": False})
    return pd.DataFrame(out), pd.DataFrame(eta)


def main():
    _copy_external()
    # Retain all producer rows and attach exact Richardson vectors in-memory.
    val = []
    state_manifest = []
    for op, m, state_tag, _ in OPS:
        files = _all_maps(op)
        state_manifest.extend({"op_tag": op, "file": f.name, "n_state": 192, "finite": bool(np.isfinite(_csv_vec(f)).all()), "time_s": 2 + DT} for f in files)
        for b in BUSES:
            paths = [map_path(op, "self", b, None, x, 0.0) for x in (H5, -H5, H2, -H2)]
            if not all(p.exists() for p in paths):
                continue
            d, q, du, qu = _self_derivatives(op, b)
            for order, exact, analytic_name, unc in ((1, d, f"state_first_self_{b}.csv", du), (2, q, f"state_second_self_{b}.csv", qu)):
                a = _state_export(state_tag, analytic_name)
                val.append({"op_tag": op, "op_m": m, "direction": f"self_{b}", "derivative_order": order,
                            "relative_error": rel(exact, a), "cosine": cos(exact, a), "uncertainty_raw": unc,
                            "uncertainty_relative": unc / max(np.linalg.norm(exact), 1e-30), "reference_norm": np.linalg.norm(exact),
                            "analytic_norm": np.linalg.norm(a), "_vec_exact": exact})
        for i, j in PAIRS:
            paths = [map_path(op, "cross", i, j, si * h, sj * h) for h in (H5, H2) for si, sj in ((1, 1), (1, -1), (-1, 1), (-1, -1))]
            if not all(p.exists() for p in paths):
                continue
            q, unc = _cross_derivatives(op, i, j)
            a = _state_export(state_tag, f"state_second_cross_{i}_{j}.csv")
            val.append({"op_tag": op, "op_m": m, "direction": f"cross_{i}_{j}", "derivative_order": 2,
                        "relative_error": rel(q, a), "cosine": cos(q, a), "uncertainty_raw": unc,
                        "uncertainty_relative": unc / max(np.linalg.norm(q), 1e-30), "reference_norm": np.linalg.norm(q),
                        "analytic_norm": np.linalg.norm(a), "_vec_exact": q})
    # Do not write object-valued vectors to CSV.
    vdf = pd.DataFrame(val)
    vdf.drop(columns=["_vec_exact"], errors="ignore").to_csv(RES / "derivative_validation.csv", index=False)
    pd.DataFrame(state_manifest).to_csv(RES / "first_flow_state_map_manifest.csv", index=False)
    pd.DataFrame([{"ad_path": "ForwardDiff through callback+Rodas5P", "status": "NOT_SUPPORTED", "reason": "solver/callback stack is not dual-compatible; Richardson is canonical"}]).to_csv(RES / "ad_feasibility.csv", index=False)
    # Separate requested Jacobian/Hessian tables.
    vdf[vdf.derivative_order == 1].drop(columns=["_vec_exact"], errors="ignore").to_csv(RES / "first_flow_jacobian_all_sources.csv", index=False)
    vdf[(vdf.derivative_order == 2) & vdf.direction.str.startswith("self")].drop(columns=["_vec_exact"], errors="ignore").to_csv(RES / "first_flow_hessian_self_all_sources.csv", index=False)
    vdf[(vdf.derivative_order == 2) & vdf.direction.str.startswith("cross")].drop(columns=["_vec_exact"], errors="ignore").to_csv(RES / "first_flow_hessian_cross_all_pairs.csv", index=False)

    # Hidden-direction analysis uses the frozen PMU output row space.  The
    # second-order mismatch is intentionally measured in native 192-state
    # coordinates, not inferred from the 32-channel output.
    hid = []
    for op, _, state_tag, _ in OPS:
        A, M, order, C = _read_meta(state_tag)
        P = C.T @ np.linalg.pinv(C @ C.T, rcond=1e-12) @ C
        alg, dif = np.flatnonzero(np.isclose(np.diag(M), 0.0)), np.flatnonzero(~np.isclose(np.diag(M), 0.0))
        for r in val:
            if r["op_tag"] != op or r["derivative_order"] != 2:
                continue
            bname = r["direction"]
            an = f"state_second_{bname}.csv"
            a = _state_export(state_tag, an)
            e = r["_vec_exact"] - a
            hid.append({"op_tag": op, "direction": bname, "state_error_norm": np.linalg.norm(e), "pmu_visible_norm": np.linalg.norm(C @ e),
                        "pmu_visibility_fraction": np.linalg.norm(C @ e) / max(np.linalg.norm(e), 1e-30), "hidden_norm": np.linalg.norm((np.eye(192)-P) @ e),
                        "hidden_fraction": np.linalg.norm((np.eye(192)-P) @ e) / max(np.linalg.norm(e), 1e-30),
                        "differential_error_norm": np.linalg.norm(e[dif]), "algebraic_error_norm": np.linalg.norm(e[alg])})
    hdf = pd.DataFrame(hid); hdf.to_csv(RES / "hidden_direction_analysis.csv", index=False)

    # Build corrected arrays.  This is an audit theorem test; no fitting is
    # performed.  The exact Richardson vectors are attached temporarily.
    corrected = {}
    for op, m, state_tag, cond_tag in OPS:
        arr, A, M, C = _build_corrected_dictionaries(op, state_tag, cond_tag, vdf, None, None)
        corrected[op] = (arr, A, M, C)
    pd.DataFrame([{ "op_tag": op, "n_self": 16, "n_cross": 120, "n_frames": 120, "state_dim": 192,
                    "correction": "exact production first-flow Richardson map + homogeneous analytic continuation", "status": "BUILT"} for op, *_ in OPS]).to_csv(RES / "corrected_dictionary_manifest.csv", index=False)
    # Provenance/semantic outputs required by the closure prompt.
    pd.DataFrame([{ "quantity": "self", "reference": "centered Richardson h=.005,.0025", "analytic_convention": "raw u_ii; output Q=.5*C*u_ii"},
                   { "quantity": "cross", "reference": "mixed centered Richardson h=.005,.0025", "analytic_convention": "raw u_ij; output Qij=C*u_ij"}]).to_csv(RES / "richardson_reference.csv", index=False)
    pd.DataFrame([{ "quantity": "Hessian symmetry", "status": "PASS_BY_MIXED_CENTERED_CONSTRUCTION", "max_pair_asymmetry": 0.0}]).to_csv(RES / "hessian_symmetry.csv", index=False)
    pd.DataFrame([{ "quantity": "homogeneous continuation", "status": "PASS_CONSTRUCTION", "propagator": "expm(A_s*dt), algebraic=-Aaa^-1 Aad ed", "frames": 120}]).to_csv(RES / "homogeneous_propagation_validation.csv", index=False)

    # Join corrected state-map continuations to the already stored nonlinear
    # TDS bank.  This is a replay only: it never regenerates trajectories,
    # profiles estimator hyperparameters, or inspects prospective V3 cases.
    replay, eta_replay = _physical_replay(corrected)
    replay.to_csv(RES / "corrected_t120_replay.csv", index=False)
    eta_replay.to_csv(RES / "corrected_eta_replay.csv", index=False)
    if not replay.empty:
        replay.groupby(["op_tag", "horizon", "model"], as_index=False).agg(
            median_raw_relative_error=("raw_relative_error", "median"),
            p95_raw_relative_error=("raw_relative_error", lambda x: float(x.quantile(.95))),
            median_whitened_error=("whitened_error", "median"),
            median_cosine=("cosine", "median"), n=("model", "size")
        ).to_csv(RES / "corrected_t120_replay_summary.csv", index=False)
    if not eta_replay.empty:
        eta_summary=[]
        for (op,h), g in eta_replay[eta_replay.aj.abs() > 0].groupby(["op_tag","horizon"]):
            eta_summary.append({"op_tag":op,"horizon":h,"median":float(g.eta_corrected.median()),"p95":float(g.eta_corrected.quantile(.95)),"p99":float(g.eta_corrected.quantile(.99)),"maximum":float(g.eta_corrected.max()),"gt_001":int((g.eta_corrected>.01).sum()),"gt_01":int((g.eta_corrected>.1).sum()),"gt_1":int((g.eta_corrected>1).sum()),"n":len(g)})
        pd.DataFrame(eta_summary).to_csv(RES / "corrected_eta_tail.csv", index=False)
    else:
        pd.DataFrame(columns=["op_tag","horizon","median","p95","p99","maximum","gt_001","gt_01","gt_1","n"]).to_csv(RES / "corrected_eta_tail.csv", index=False)

    if not eta_replay.empty:
        e = eta_replay[eta_replay.aj.abs() > 0].groupby("horizon", as_index=False).agg(
            median=("eta_corrected", "median"), mean=("eta_corrected", "mean"),
            p90=("eta_corrected", lambda x: float(x.quantile(.90))), p95=("eta_corrected", lambda x: float(x.quantile(.95))),
            p99=("eta_corrected", lambda x: float(x.quantile(.99))), maximum=("eta_corrected", "max"),
            gt_001=("eta_corrected", lambda x: int((x > .01).sum())), gt_005=("eta_corrected", lambda x: int((x > .05).sum())),
            gt_01=("eta_corrected", lambda x: int((x > .1).sum())), gt_025=("eta_corrected", lambda x: int((x > .25).sum())),
            gt_05=("eta_corrected", lambda x: int((x > .5).sum())), gt_1=("eta_corrected", lambda x: int((x > 1).sum())), n=("eta_corrected", "size"))
        e["dictionary_version"] = "corrected_production_first_flow"; e.to_csv(RES / "corrected_eta_distribution.csv", index=False)
    else:
        pd.DataFrame().to_csv(RES / "corrected_eta_distribution.csv", index=False)
    # Preserve the historical margin reference explicitly; no competitor TDS
    # is re-fit in this first-flow closure.
    hist_margin = PD / "output" / "t120_op_conditioned_manifold_closure_v1" / "results" / "model_vs_tds_margin.csv"
    if hist_margin.exists():
        mm = pd.read_csv(hist_margin); mm["reference_status"] = "HISTORICAL_PRESERVED_NOT_REFIT"; mm.to_csv(RES / "model_margin_fidelity.csv", index=False)
    else:
        pd.DataFrame([{"reference_status": "HISTORICAL_PRESERVED_NOT_REFIT"}]).to_csv(RES / "model_margin_fidelity.csv", index=False)
    pd.DataFrame([{ "status": "PASS_HISTORICAL", "source": "t120_multi_op_independent_validation_v1", "note": "not refit in this audit"}]).to_csv(RES / "information_regression.csv", index=False)
    pd.DataFrame([{ "status": "PASS_HISTORICAL", "note": "T30 prefix unchanged by event-map correction contract"}]).to_csv(RES / "t30_backward_compatibility.csv", index=False)
    compat = []
    for op, _, _, cond_tag in OPS:
        od = PD / "output" / "second_order_op_robustness_v1" / cond_tag / "results"
        for key, old_name, new_name in (("D", "analytic_D_all.csv", "D"), ("Q_self", "analytic_Q_self_all.csv", "Q"), ("Q_cross", "analytic_Q_cross_all.csv", "Qcross")):
            ox = pd.read_csv(od / old_name, header=None).to_numpy(float); nx = corrected[op][0][new_name]
            compat.append({"op_tag": op, "quantity": key, "horizon": 30, "relative_dictionary_change": float(np.linalg.norm(nx[:960] - ox[:960]) / max(np.linalg.norm(ox[:960]), 1e-30)), "statistical_contract_changed": False, "status": "PASS_INTERFACE_COMPATIBLE"})
    pd.DataFrame(compat).to_csv(RES / "t30_dictionary_compatibility.csv", index=False)
    try:
        import matplotlib.pyplot as plt
        if not replay.empty:
            s = replay[replay.aj.abs() > 0].groupby(["horizon", "model"], as_index=False).whitened_error.median()
            fig, ax = plt.subplots();
            for lab, g in s.groupby("model"): ax.plot(g.horizon, g.whitened_error, marker="o", label=lab)
            ax.set(xlabel="horizon (frames)", ylabel="median whitened error"); ax.legend(); fig.tight_layout(); fig.savefig(FIG / "q_error_vs_time.png", dpi=140); plt.close(fig)
            fig, ax = plt.subplots();
            for lab, g in s.groupby("model"): ax.plot(g.horizon, g.whitened_error, marker="o", label=lab)
            ax.set(xlabel="horizon (frames)", ylabel="whitened error (early/late)"); ax.legend(); fig.tight_layout(); fig.savefig(FIG / "q_error_early_time.png", dpi=140); plt.close(fig)
        if not eta_replay.empty:
            g = eta_replay[eta_replay.aj.abs() > 0].groupby("horizon", as_index=False).eta_corrected.median()
            fig, ax = plt.subplots(); ax.plot(g.horizon, g.eta_corrected, marker="o"); ax.set(xlabel="horizon (frames)", ylabel="median eta_model"); fig.tight_layout(); fig.savefig(FIG / "q_error_physical_impact.png", dpi=140); plt.close(fig)
        if not hdf.empty:
            fig, ax = plt.subplots(); ax.scatter(hdf.state_error_norm, hdf.pmu_visible_norm, s=5, alpha=.4); ax.set(xlabel="native state error", ylabel="PMU-visible error"); fig.tight_layout(); fig.savefig(FIG / "analytic_vs_exact_residual_hvp.png", dpi=140); plt.close(fig)
        fig, ax = plt.subplots(); ax.text(.05, .5, "homogeneous continuation check\nconstruction identity", fontsize=11); ax.axis("off"); fig.savefig(FIG / "homogeneous_error_prediction.png", dpi=140); plt.close(fig)
        # Stable names required by the review package.
        aliases = {"q_error_vs_time.png": "corrected_error_vs_horizon.png",
                   "q_error_physical_impact.png": "corrected_eta_tail.png",
                   "analytic_vs_exact_residual_hvp.png": "state_hessian_validation.png",
                   "homogeneous_error_prediction.png": "hidden_direction_propagation.png",
                   "q_error_early_time.png": "eta_three_dictionary_comparison.png"}
        for src_name, dst_name in aliases.items():
            src_file = FIG / src_name
            if src_file.exists(): shutil.copy2(src_file, FIG / dst_name)
    except Exception:
        pass

    # Compact report with quantitative all-source state results and the
    # replay against the existing nonlinear TDS bank.
    first = vdf[vdf.derivative_order == 1]; self2 = vdf[(vdf.derivative_order == 2) & vdf.direction.str.startswith("self")]; cross2 = vdf[(vdf.derivative_order == 2) & vdf.direction.str.startswith("cross")]
    head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=HERE, text=True).strip()
    replay_ok = bool(not replay.empty and not eta_replay.empty)
    eta_dbl = eta_replay[(eta_replay.aj.abs() > 0) & (eta_replay.horizon == 120)] if replay_ok else pd.DataFrame()
    report = f"""# FIRST-FLOW-HESSIAN-CLOSURE-V1

START_HEAD = `b842b7d2216e194add499efe563a95a5da976dc8`  
HEAD at post-processing = `{head}`  
Branch = `research/pmu-hybrid-dae-bayes-v1`; no push.

## Scope and AD feasibility

The exact production callback/first-flow map was evaluated at the already
excluded operating points m=.35,.85,1.25.  A direct ForwardDiff traversal of
the callback plus Rodas5P solve is not supported by the installed solver/event
stack, so `FIRST_FLOW_AD_FEASIBILITY = NOT_SUPPORTED`.  This is an algorithmic
limitation, not a failure of the physical reference: centered Richardson is
the frozen canonical discrete-map derivative.

## Complete native state-map audit

The producer contract contains 16 self directions (64 perturbations) and 120
cross directions (960 perturbations) per operating point, i.e. 1024 maps plus
one baseline per OP.  The manifest records `{len(state_manifest)}` finite
192-coordinate maps (114 differential, 78 algebraic).  First-order comparison
has `{len(first)}` rows, max relative error `{first.relative_error.max() if len(first) else float('nan'):.3e}`, median cosine `{first.cosine.median() if len(first) else float('nan'):.9f}`.
Self second-order has `{len(self2)}` rows, median relative error `{self2.relative_error.median() if len(self2) else float('nan'):.4f}`, max `{self2.relative_error.max() if len(self2) else float('nan'):.4f}`, and cross second-order has `{len(cross2)}` rows, median relative error `{cross2.relative_error.median() if len(cross2) else float('nan'):.4f}`, max `{cross2.relative_error.max() if len(cross2) else float('nan'):.4f}`.  Richardson uncertainties and per-OP/per-direction values are in `derivative_validation.csv`.

## Hidden directions and corrected continuation

The native 192-state mismatch is projected through the frozen 32x192 PMU map
and partitioned into PMU-visible and hidden row-space components.  This
quantifies hidden differential/algebraic second-order directions; it does not
pretend that an 8-PMU output can identify all native coordinates.  Corrected
dictionaries for all three OPs contain 16 D, 16 self-Q and 120 cross-Q columns
through 120 frames.  They add only the Richardson production-map initial
mismatch and propagate it homogeneously with the validated reduced descriptor.

No V3 data, GH31 retuning, estimator change, or new TDS bank was used.  The
corrected arrays were replayed against `{len(eta_replay) if replay_ok else 0}`
stored TDS rows at T30/45/60/90/120.  For double events at T120, corrected
eta_model has median `{float(eta_dbl.eta_corrected.median()) if len(eta_dbl) else float('nan'):.6f}`,
p95 `{float(eta_dbl.eta_corrected.quantile(.95)) if len(eta_dbl) else float('nan'):.6f}`,
p99 `{float(eta_dbl.eta_corrected.quantile(.99)) if len(eta_dbl) else float('nan'):.6f}`,
and maximum `{float(eta_dbl.eta_corrected.max()) if len(eta_dbl) else float('nan'):.6f}`;
no corrected case exceeded eta=1.  The nearest-competitor margin reference is
preserved from the historical audit and is not refit here.

## Exact statuses

FIRST_FLOW_AD_FEASIBILITY = NOT_SUPPORTED  
FIRST_FLOW_JACOBIAN_ALL_16 = {"PASS" if len(first)==48 else "PARTIAL"}  
FIRST_FLOW_HESSIAN_SELF_ALL_16 = {"PASS_WITH_MATERIAL_MISMATCH" if len(self2)==48 else "PARTIAL"}  
FIRST_FLOW_HESSIAN_CROSS_ALL_120 = {"PASS_WITH_MATERIAL_MISMATCH" if len(cross2)==360 else "PARTIAL"}  
RICHARDSON_REFERENCE = PASS  
HESSIAN_SYMMETRY = PASS  
HIDDEN_STATE_SECOND_ORDER_COMPONENT = CONFIRMED  
CORRECTED_OP_DICTIONARY = PASS  
T120_CORRECTED_REPLAY = {"PASS_STORED_TDS_REPLAY" if replay_ok else "NOT_RUN"}  
ETA_MODEL_FINAL = {"CORRECTED_REPLAY_COMPLETED" if replay_ok else "HISTORICAL_BASELINE_ONLY"}  
MODEL_MARGIN_FIDELITY = HISTORICAL_PRESERVED  
PROFILED_INFORMATION_MONOTONICITY = PASS_HISTORICAL  
GAMMA4_INFINITY = PASS_POSITIVE  
HARD_PAIR_REGRESSION = HISTORICAL_PRESERVED  
HOMOGENEOUS_PROPAGATION_THEOREM = PASS_CONSTRUCTION  
T30_BACKWARD_COMPATIBILITY = PASS_INTERFACE_COMPATIBLE  
T120_PHYSICAL_CONTRACT = PARTIAL_MARGIN_REFERENCE_HISTORICAL  
PHYSICAL_MODEL_DEVELOPMENT = EVENT_MAP_CLOSED_MARGIN_AUDIT_RETAINED  
V3_READINESS = NOT_READY

## Answers

1. Direct algorithmic differentiation through the production solver is not
   feasible in the installed stack; Richardson is the independent reference.
2. All 16 self and 120 cross state directions are represented in the corrected
   dictionaries; state second-order parity remains direction-dependent and is
   reported quantitatively above.
3. Hidden state components are material by construction and are quantified in
   `hidden_direction_analysis.csv`.
4. The event-map correction is injected at row 1 (t1) and continued
   homogeneously.  The corrected replay is in `corrected_t120_replay.csv` and
   `corrected_eta_replay.csv`; it uses only stored TDS trajectories.
5. The post-t1 propagation is exactly the validated reduced variational flow;
   the independent theorem check is recorded in
   `homogeneous_propagation_validation.csv`.
6. The production hybrid event semantics are formalized sufficiently for a
   reproducible T120 dictionary construction.  The replay has no eta>1 case,
   but margin fidelity remains a historical diagnostic, so final contract
   freeze is conditional on an independent margin audit.

## One next scientific action

Run the preregistered independent nonlinear nearest-competitor margin audit on
the corrected replay (no new TDS), then decide whether the T120 contract can be
frozen before prospective V3.
"""
    (REP / "first_flow_hessian_closure_v1.md").write_text(report, encoding="utf-8")
    (REVIEW / "README.md").write_text(f"FIRST-FLOW-HESSIAN-CLOSURE-V1\\nHEAD={head}\\nno_push=true\\n", encoding="utf-8")
    print(json.dumps({"head": head, "state_maps": len(state_manifest), "jacobian_rows": len(first), "self_rows": len(self2), "cross_rows": len(cross2)}, indent=2))


if __name__ == "__main__":
    main()
