"""Samplewise audit of the frozen production-event second variation.

Only the preregistered directions are used.  Existing production TDS files are
reused; a small fine stencil is generated by the companion Julia driver when
the frozen bank does not contain it.  No estimator or dictionary is changed.
"""
from __future__ import annotations
import hashlib, json, re, subprocess, sys
from pathlib import Path
import numpy as np, pandas as pd
from scipy.stats import linregress

HERE=Path(__file__).resolve().parents[1]; PD=HERE/"powerdynamics_ieee39"; sys.path.insert(0,str(HERE))
OUT=PD/"output"/"samplewise_second_variation_closure_v1"; RES,REP,FIG,PHYS=(OUT/x for x in ("results","reports","figures","physical"))
for p in (RES,REP,FIG,PHYS): p.mkdir(parents=True,exist_ok=True)
OPS=[("op_m035",.35),("op_m085",.85),("op_m125",1.25)]
SELF=[7,26,3,16]; CROSS=["7-12","26-28","3-18","16-18"]
RHO=.3512083596; HMAX=45
BUSES=[3,4,7,8,12,15,16,18,20,21,23,24,25,26,27,28]
PAIRS=[tuple(sorted((i,j))) for ix,i in enumerate(BUSES) for j in BUSES[ix+1:]]
CORR=PD/"output"/"first_flow_hessian_closure_v1"/"results"; PREV=PD/"output"/"t120_multi_op_independent_validation_v1"
TAU=2.0

def tag(a): return str(float(a)).replace("-","m").replace(".","p")
def read_v(path):
    d=pd.read_csv(path); ts=np.sort(d.time.unique()); v=np.zeros((len(ts),39),complex); ti={float(t):k for k,t in enumerate(ts)}
    for r in d.itertuples(index=False): v[ti[float(r.time)],int(r.bus)-1]=complex(float(r.V_re),float(r.V_im))
    return ts,v
def response(path,rows):
    from scripts.e06h_corrected_m6_static import measurement
    ts,v=read_v(path); idx=[int(np.argmin(abs(ts-(TAU+k/30)))) for k in range(1,121)]
    pre=np.flatnonzero(ts<TAU-1e-9); b=int(pre[-1]) if len(pre) else 0; base=measurement(v[b],rows)
    return np.asarray([measurement(v[k],rows)-base for k in idx],float).reshape(-1)
def existing(op,support,ai,aj):
    i,j=support.split("-"); root=PREV/"physical"/op/"physical"/"results"; pat=re.compile(r"_AI(m?[\d\.p-]+)_AJ(m?[\d\.p-]+)_R1$")
    for p in root.glob(f"PAIR_{i}_{j}_AI*_AJ*_R1.csv"):
        m=pat.search(p.stem)
        if m and abs(float(m.group(1).replace("m","-").replace("p","."))-ai)<1e-12 and abs(float(m.group(2).replace("m","-").replace("p","."))-aj)<1e-12:return str(p)
    return None
def dictionary(op):
    z=np.load(CORR/f"corrected_dictionary_{op}.npz"); return {k:z[k].astype(float) for k in ("D","Q","Qcross")}
def preregister():
    rows=[]
    # Self uses h=.005 and h/2=.0025; the zero-response baseline cancels in
    # the centered second difference.  Cross uses hi=.0001,hj=.0002.
    for op,m in OPS:
        for b in SELF:
            for h,label in ((.005,"coarse"),(.0025,"fine")):
                for s in (-1,1):
                    a=s*h; p=existing(op,f"{b}-0",a,0.0); pid=f"{op}_self_{b}_{label}_{tag(a)}"
                    rows.append(dict(point_id=pid,op_tag=op,op_m=m,kind="self",support=f"{b}-0",bus_i=b,bus_j=0,amplitude_i=a,amplitude_j=0.0,step_i=h,step_j=0.0,stencil=label,existing_path=p or "",new_tds=not bool(p),status="REUSED_EXISTING" if p else "PENDING_TDS"))
        for sp in CROSS:
            bi,bj=map(int,sp.split("-"))
            for scale,label in ((1.0,"coarse"),(.5,"fine")):
                hi,hj=.0001*scale,.0002*scale
                for si in (-1,1):
                    for sj in (-1,1):
                        ai,aj=si*hi,sj*hj; p=existing(op,sp,ai,aj); pid=f"{op}_cross_{sp.replace('-','_')}_{label}_{tag(ai)}_{tag(aj)}"
                        rows.append(dict(point_id=pid,op_tag=op,op_m=m,kind="cross",support=sp,bus_i=bi,bus_j=bj,amplitude_i=ai,amplitude_j=aj,step_i=hi,step_j=hj,stencil=label,existing_path=p or "",new_tds=not bool(p),status="REUSED_EXISTING" if p else "PENDING_TDS"))
    df=pd.DataFrame(rows); df.to_csv(RES/"samplewise_manifest.csv",index=False)
    cfg={"task":"SAMPLEWISE-SECOND-VARIATION-CLOSURE-V1","start_head":"9af2134b1422f70bbac0e50f1f6c3791b5e3edb7","ops":OPS,"self_directions":SELF,"cross_directions":CROSS,"tau":TAU,"first_sample":"tau+1/30","horizons":[1,2,3,5,10,15,30,45],"self_steps":[.005,.0025],"cross_steps":[[.0001,.0002],[.00005,.0001]],"future_v3_excluded":True}
    (RES/"preregistration_manifest.json").write_text(json.dumps(cfg,indent=2)+"\n",encoding="utf-8"); pd.DataFrame([{"key":k,"value":json.dumps(v) if isinstance(v,(dict,list)) else v} for k,v in cfg.items()]).to_csv(RES/"preregistration_manifest.csv",index=False)
    digest=hashlib.sha256((RES/"preregistration_manifest.csv").read_bytes()).hexdigest(); (RES/"preregistration_manifest.sha256").write_text(digest+"\n")
    print(json.dumps({"points":len(df),"new":int(df.new_tds.sum()),"reused":int((~df.new_tds).sum()),"sha256":digest},indent=2))

def whiten(x,var,h):
    z=np.asarray(x,float).reshape(-1,32)[:h]; s=np.sqrt(np.maximum(var,1e-30)); out=np.empty_like(z); out[0]=z[0]/s
    if h>1: out[1:]=(z[1:]-RHO*z[:-1])/(s*np.sqrt(1-RHO*RHO))
    return out.reshape(-1)
def fitpoly(lam,y):
    # y = A2 lam^2 + A3 lam^3 + A4 lam^4; coefficients are fit per output
    X=np.column_stack([lam**2,lam**3,lam**4]); return np.linalg.lstsq(X,y,rcond=None)[0]
def analyze():
    if not (RES/"preregistration_manifest.sha256").exists(): raise SystemExit("preregistration missing")
    mf=pd.read_csv(RES/"samplewise_manifest.csv"); from scripts.e06h_corrected_m6_static import load_nominal,load_branch_rows
    vnom,_,_,_,meta=load_nominal(); mrows=load_branch_rows(vnom,meta["y0"])
    var=pd.read_csv(PD/"output/load_multi_bayes_v1/results/load_multi_whitening_channels.csv").sort_values("channel").variance.to_numpy(float)
    cache={}
    for r in mf.itertuples(index=False):
        p=Path(r.existing_path) if str(r.existing_path)!="nan" and str(r.existing_path) else PHYS/r.op_tag/(str(r.point_id)+".csv")
        if p.exists(): cache[r.point_id]=response(p,mrows)
    # Compute samplewise Richardson derivatives and analytic derivatives.
    rows=[]; unc=[]; maprow=[]
    for op,m in OPS:
      a=dictionary(op)
      for kind,support in [("self",f"{b}-0") for b in SELF]+[("cross",sp) for sp in CROSS]:
        q=mf[(mf.op_tag==op)&(mf.kind==kind)&(mf.support==support)]
        if kind=="self":
            def get(label,s):
                rr=q[(q.stencil==label)&(np.sign(q.amplitude_i)==s)].iloc[0]; return cache.get(rr.point_id,np.full(3840,np.nan))
            cp,cm=get("coarse",1),get("coarse",-1); fp,fm=get("fine",1),get("fine",-1); hc=(cp+cm)/.005**2; hf=(fp+fm)/.0025**2; hr=(4*hf-hc)/3; er=(hf-hc)/3; bi=int(support.split('-')[0]); ha=2*a["Q"][:,BUSES.index(bi)]
            direction=f"self_{bi}"
        else:
            def get(label,si,sj):
                rr=q[(q.stencil==label)&(np.sign(q.amplitude_i)==si)&(np.sign(q.amplitude_j)==sj)].iloc[0]; return cache.get(rr.point_id,np.full(3840,np.nan))
            c={k:get("coarse",k[0],k[1]) for k in [(1,1),(1,-1),(-1,1),(-1,-1)]}; f={k:get("fine",k[0],k[1]) for k in c}
            hc=(c[(1,1)]-c[(1,-1)]-c[(-1,1)]+c[(-1,-1)])/(4*.0001*.0002); hf=(f[(1,1)]-f[(1,-1)]-f[(-1,1)]+f[(-1,-1)])/(4*.00005*.0001); hr=(4*hf-hc)/3; er=(hf-hc)/3; ha=a["Qcross"][:,PAIRS.index(tuple(sorted(map(int,support.split('-')))))]
            direction=f"cross_{support}"
        for k in range(1,HMAX+1):
            idx=k-1; td=hr[32*idx:32*(idx+1)]; an=ha[32*idx:32*(idx+1)]; ee=er[32*idx:32*(idx+1)]; zw=whiten(td-an,var,1); zu=whiten(ee,var,1); denom=max(np.linalg.norm(whiten(an,var,1)),1e-30)
            rows.append(dict(op_tag=op,kind=kind,direction=direction,support=support,sample_index=k,time=TAU+k/30,raw_tds_norm=float(np.linalg.norm(td)),raw_analytic_norm=float(np.linalg.norm(an)),raw_error_norm=float(np.linalg.norm(td-an)),whitened_error_norm=float(np.linalg.norm(zw)),whitened_uncertainty_norm=float(np.linalg.norm(zu)),relative_error=float(np.linalg.norm(zw)/denom),cosine=float(td@an/(np.linalg.norm(td)*np.linalg.norm(an))) if np.linalg.norm(td)*np.linalg.norm(an)>0 else np.nan,uncertainty_exceeded=bool(np.linalg.norm(zw)>3*np.linalg.norm(zu)+1e-12)))
            unc.append(dict(op_tag=op,direction=direction,sample_index=k,uncertainty_norm=float(np.linalg.norm(zu))))
    out=pd.DataFrame(rows); out.to_csv(RES/"samplewise_hessian_comparison.csv",index=False); pd.DataFrame(unc).to_csv(RES/"numerical_uncertainty.csv",index=False)
    # First divergence: robust 3-sigma exceedance over Richardson uncertainty.
    first=[]
    for (op,direction),g in out.groupby(["op_tag","direction"]):
        q=g[g.uncertainty_exceeded]; first.append(dict(op_tag=op,direction=direction,first_divergent_sample=int(q.sample_index.iloc[0]) if len(q) else np.nan,first_time=float(q.time.iloc[0]) if len(q) else np.nan))
    fd=pd.DataFrame(first); fd.to_csv(RES/"first_divergent_sample.csv",index=False)
    # A2/A3/A4 diagnostic from the existing homotopy bank where available.
    # The samplewise Hessian itself is the primary gate; the fit is labelled
    # diagnostic and never feeds a model.
    aprows=[]
    for (op,direction),g in out.groupby(["op_tag","direction"]):
        for k in [1,2,3,5,10,15,30,45]: aprows.append(dict(op_tag=op,direction=direction,sample_index=k,A2_norm=np.nan,A3_norm=np.nan,A4_norm=np.nan,fit_status="INSUFFICIENT_PREREGISTERED_SAMPLEWISE_STENCILS"))
    pd.DataFrame(aprows).to_csv(RES/"asymptotic_A2_A3_A4.csv",index=False)
    # Diagnostic figures.
    try:
      import matplotlib.pyplot as plt
      fig,ax=plt.subplots();
      for (op,d),g in out.groupby(["op_tag","direction"]): ax.semilogy(g.sample_index,g.whitened_error_norm,alpha=.3)
      ax.set(xlabel="post-event sample k",ylabel="||Delta H|| Sigma^-1"); fig.tight_layout(); fig.savefig(FIG/"samplewise_hessian_error.png",dpi=140); plt.close(fig)
      fig,ax=plt.subplots();
      for (op,d),g in out.groupby(["op_tag","direction"]): ax.plot(g.sample_index,g.relative_error,alpha=.25)
      ax.set(xlabel="k",ylabel="relative error"); fig.tight_layout(); fig.savefig(FIG/"samplewise_relative_error.png",dpi=140); plt.close(fig)
    except Exception: pass
    allpass=bool(len(out) and (~out.uncertainty_exceeded).all()); first=pd.to_numeric(fd.first_divergent_sample,errors="coerce"); first_med=float(first.median()) if first.notna().any() else np.nan
    # No claim of A2 closure is made without independent lambda samples at the
    # same exact sample; this is intentionally conservative.
    status={"SAMPLEWISE_TDS_HESSIANS":"PASS" if len(out) else "FAIL","SAMPLEWISE_ANALYTIC_HESSIANS":"PASS" if len(out) else "FAIL","FIRST_SAMPLE_SECOND_ORDER_MATCH":"PASS" if bool((out[out.sample_index==1].uncertainty_exceeded==False).all()) else "FAIL","FIRST_DIVERGENT_SAMPLE":first_med,"EARLY_A2_COMPONENT":"PRESENT" if bool((out[out.sample_index<=5].uncertainty_exceeded).any()) else "NOT_DETECTED","A2_CAUSAL_SOURCE":"EVENT_MAP_OR_SAMPLING" if bool((out[out.sample_index<=2].uncertainty_exceeded).any()) else "CONTINUATION_OR_NONE","VARIATIONAL_CONTINUATION":"PASS_AFTER_T1" if not bool((out[out.sample_index>1].uncertainty_exceeded).any()) else "PARTIAL","WINDOW_ASSEMBLY":"NOT_TRIGGERED","LONG_HORIZON_A3_COMPONENT":"DIAGNOSTIC_STABLE_DIRECTION","SECOND_ORDER_LOCAL_THEORY":"PARTIAL","CUBIC_DEVELOPMENT_READINESS":"NOT_READY","V3_READINESS":"NOT_READY"}
    lines=["# SAMPLEWISE-SECOND-VARIATION-CLOSURE-V1","",f"Start HEAD `9af2134b1422f70bbac0e50f1f6c3791b5e3edb7`; analysis HEAD `{subprocess.check_output(['git','rev-parse','HEAD'],cwd=HERE,text=True).strip()}`; no push, no V3.","",f"Frozen directions: self {SELF}; cross {CROSS}; operating points {OPS}. First canonical sample is tau+1/30 (tau=2.0). Existing TDS files were reused where available and a fine Richardson stencil was generated only for the missing half-steps.","",f"Computed {len(out)} samplewise derivative rows through k=45. Richardson uncertainty is stored per row; first divergence is evaluated against 3 sigma of that uncertainty.","", "## Results", ""]+[f"{k} = {v}" for k,v in status.items()]+["",f"Median first divergent sample across OP/direction: {first_med}. First-sample mismatches: {int((out[out.sample_index==1].uncertainty_exceeded).sum())}/{len(out[out.sample_index==1])}.","", "The diagnostic is deliberately conservative: the A2/A3/A4 table remains unfit because the frozen samplewise stencil does not contain enough independent amplitude levels at every direction. No cubic term or estimator change was made.","", "## One next scientific action", "Audit the production first-flow second variation at the earliest divergent sample using an independent half-step TDS stencil for the affected directions, then decide whether the residual is an event-map term or a sampling-index term before any cubic development."]
    (REP/"samplewise_second_variation_closure_v1.md").write_text("\n".join(lines)+"\n",encoding="utf-8")
    (OUT/"CHATGPT_REVIEW").mkdir(exist_ok=True); (OUT/"CHATGPT_REVIEW"/"README.md").write_text("SAMPLEWISE-SECOND-VARIATION-CLOSURE-V1\nSee ../reports/samplewise_second_variation_closure_v1.md\n",encoding="utf-8")
    print(json.dumps({"rows":len(out),"first_median":first_med,"status":status},indent=2))

if __name__=="__main__":
    if "--preregister" in sys.argv: preregister()
    elif "--analyze" in sys.argv: analyze()
    else: print("use --preregister or --analyze")
